Ehas/routes/user.php
<?php


use App\Http\Controllers\Users\UserHomeController;
use App\Http\Controllers\AppointmentPaymentController;
use App\Http\Controllers\ProfileController;

Route::middleware(['auth', 'role:patient'])->group(function (){
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::get('/get-appointment/{id}', [AppointmentPaymentController::class, 'get_appointment'])->name('appointment.get');
    Route::post('/get-appointment/{id}', [AppointmentPaymentController::class, 'post_appointment'])->name('appointment.post');
    Route::get('/order-confirmed/{orderid}', [AppointmentPaymentController::class, 'confirmation'])->name('appointment.confirmation');
    
});


Route::prefix('/users')->middleware('auth')->group(function(){

    Route::get('/dashboard', [UserHomeController::class ,'index'])->name('user.dashboard');
    Route::any('/profile', [UserHomeController::class ,'profile'])->name('user.profile');
    Route::any('/medical-history', [UserHomeController::class ,'medicalHistory'])->name('user.medical_history');
    Route::any('/health-prediction', [UserHomeController::class ,'healthPrediction'])->name('user.health_prediction');
    Route::get('/appointments_list', [UserHomeController::class ,'appointmentList'])->name('user.appointment.list');

});

Ehas/routes/web.php
<?php


use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Admins\AdminController;
use App\Http\Controllers\Admins\CategoryController;
use App\Http\Controllers\Admins\GeneralProblemController;
use App\Http\Controllers\Admins\MedcomController;
use App\Http\Controllers\Admins\MedestController;
use App\Http\Controllers\Admins\SpecificProblemController;
use App\Http\Controllers\Users\UserHomeController;

use App\Http\Controllers\MainController;
use App\Http\Controllers\ChatBotController;
use App\Models\Medvariant;
use App\Http\Controllers\Admins\MedvarController;
use App\Http\Controllers\Admins\MedController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/dashboard', function () {
//     return view('users.dashboard');
// })->middleware(['auth', 'verified'])->name('dashboard');


Route::get('/', [MainController::class, 'index'])->name('home');
Route::get('/contact-us', [MainController::class, 'contact'])->name('contact');
Route::get('/services', [MainController::class, 'service'])->name('service');
Route::get('/about-us', [MainController::class, 'about'])->name('about');
Route::get('/consultants', [MainController::class, 'consultants'])->name('consultants');
Route::get('/consultant/{id}', [MainController::class, 'consultant_profile'])->name('consultant.profile');
Route::get('/ehas-live-chat', [MainController::class, 'liveChat'])->name('live.chat');

Route::get('/privacy-policy', [MainController::class, 'privary_policy'])->name('privacy_policy');
Route::get('/terms-of-use', [MainController::class, 'terms_of_use'])->name('terms_of_use');
Route::get('/support', [MainController::class, 'support'])->name('support');

Route::post('/get-chat-message', [ChatBotController::class, 'getMessage'])->name('chat.message');



require __DIR__.'/auth.php';

require __DIR__.'/user.php';

require __DIR__.'/doctor.php';

require __DIR__.'/support.php';


// Admin user Route List
Route::group(['middleware' => ['auth:admin', 'verified'], 'prefix' => 'kadmin-user'], function () {
    Route::get('/dashboard', [AdminController::class ,'index'])->name('admin.dashboard');
    
    
    Route::get('/admins', [AdminController::class ,'admin_list'])->name('admin.admin_list');
    Route::get('/admins-create', [AdminController::class ,'admin_create'])->name('admin.admin_create');
    
    Route::get('/doctors', [AdminController::class ,'doctor_list'])->name('admin.doctor_list');
    Route::get('/patients', [AdminController::class ,'patient_list'])->name('admin.patient_list');
    Route::get('/supports', [AdminController::class ,'support_list'])->name('admin.support_list');
    
    Route::get('/appointments', [AdminController::class ,'appointments'])->name('admin.appointments');
    Route::get('/appointments/{id}', [AdminController::class ,'appointments_list'])->name('admin.appointments_list');
    Route::get('/appointments-sold', [AdminController::class ,'appointment_sold'])->name('admin.appointments_sold');
    Route::get('/earnings', [AdminController::class ,'earnings'])->name('admin.earnings');
    
    Route::get('/prescriptions', [AdminController::class ,'prescriptions'])->name('admin.prescriptions');
    
    
    Route::any('/categories-delete/{id}', [CategoryController::class ,'delete'])->name('categories.delete');
    Route::any('/medtests-delete/{id}', [MedestController::class ,'delete'])->name('medtests.delete');
    Route::any('/medcoms-delete/{id}', [MedcomController::class ,'delete'])->name('medcoms.delete');
    Route::any('/medvars-delete/{id}', [MedvarController::class ,'delete'])->name('medvars.delete');
    Route::any('/meds-delete/{id}', [MedController::class ,'delete'])->name('meds.delete');
    
    Route::any('/general-delete/{id}', [GeneralProblemController::class ,'delete'])->name('general.delete');
    Route::any('/specific-delete/{id}', [SpecificProblemController::class ,'delete'])->name('specific.delete');
    
    Route::resource('/categories', CategoryController::class);
    Route::resource('/medtests', MedestController::class);
    Route::resource('/medcoms', MedcomController::class);
    Route::resource('/medvars', MedvarController::class);
    Route::resource('/meds', MedController::class);
    
    Route::resource('/general', GeneralProblemController::class);
    Route::resource('/specific', SpecificProblemController::class);
    
    Route::any('/status-change', [AdminController::class ,'statusChange'])->name('status.change');
    
    
});


require __DIR__.'/adminauth.php';

Ehas/app/Http/Controllers/Admins/MedController.php
<?php

namespace App\Http\Controllers\Admins;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Medicine;
use Redirect,Response;
use App\Models\Medvariant;
use App\Models\Medcompany;

class MedController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
        view()->share('module', 'Medicine');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $data = Medicine::query();
        $data = $data->paginate(5);
        $rank = $data->firstItem();
        return view('admins.meds.index', compact('data','rank'));
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $variants = Medvariant::where('status', 1)->get();
        $companies = Medcompany::where('status', 1)->get();
        return view('admins.meds.create', ['variants' => $variants, 'companies' => $companies]);
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'org_name' => ['required', 'string', 'max:255'],
            'com_name' => ['required', 'string', 'max:255'],
            'medvariant_id' => ['required', 'string', 'max:255'],
            'medvariant_id' => ['required', 'string', 'max:255'],
        ]);
        
        
        $med = new Medicine();
        $med->org_name = $request->org_name;
        $med->com_name = $request->com_name;
        $med->age_limit = $request->age_limit;
        $med->details = $request->details;
        $med->medvariant_id = $request->medvariant_id;
        $med->medcompany_id = $request->medcompany_id;
        $med->status = $request->status == 'on' ? 1 : 0;
        
        if($med->save()){
            return Redirect::route('meds.index')->withSuccess('Great! New Medicine added successfully.');
        }
        
        return Redirect::route('meds.index')->withError('Sorry! Medicine add Failed.');
        
    }
    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $data = Medicine::findOrFail($id);
        $variants = Medvariant::where('status', 1)->get();
        $companies = Medcompany::where('status', 1)->get();
        return view('admins.meds.edit', compact('data', 'variants', 'companies'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'org_name' => ['required', 'string', 'max:255'],
            'com_name' => ['required', 'string', 'max:255'],
            'medvariant_id' => ['required', 'string', 'max:255'],
            'medvariant_id' => ['required', 'string', 'max:255'],
        ]);
        
        $med = Medicine::findOrFail($id);
        $med->org_name = $request->org_name;
        $med->com_name = $request->com_name;
        $med->age_limit = $request->age_limit;
        $med->details = $request->details;
        $med->medvariant_id = $request->medvariant_id;
        $med->medcompany_id = $request->medcompany_id;
        $med->status = $request->status == 'on' ? 1 : 0;
        
        if($med->save()){
            return Redirect::route('meds.index')->withSuccess('Great! Medicine updated successfully.');
        }
        
        return Redirect::route('meds.index')->withError('Sorry! Medicine updated Failed.');
        
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function delete($id)
    {
        Medicine::destroy($id);
        return Redirect::route('meds.index')->withSuccess('Great! Medicine deleted successfully.');
    }
    

}

Ehas/app/Http/Controllers/Admins/MedvarController.php
<?php

namespace App\Http\Controllers\Admins;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Medvariant;
use Redirect,Response;

class MedvarController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
        view()->share('module', 'Medicine Variant');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $data = Medvariant::query();
        $data = $data->paginate(5);
        $rank = $data->firstItem();
        return view('admins.meds.medvars.index', compact('data','rank'));
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admins.meds.medvars.create');
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => ['required', 'string', 'max:255'],
        ]);
        
        
        $medvar = new Medvariant();
        $medvar->title = $request->title;
        $medvar->details = $request->details;
        $medvar->status = $request->status == 'on' ? 1 : 0;
        
        if($medvar->save()){
            return Redirect::route('medvars.index')->withSuccess('Great! New Medicine Variant added successfully.');
        }
        
        return Redirect::route('medvars.index')->withError('Sorry! New Medicine Variant add Failed.');
        
    }
    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $data = Medvariant::findOrFail($id);
        return view('admins.meds.medvars.edit', compact('data'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => ['required', 'string', 'max:255'],
        ]);
        
        $medvar = Medvariant::findOrFail($id);
        
        $medvar->title = $request->title;
        $medvar->details = $request->details;
        $medvar->status = $request->status == 'on' ? 1 : 0;
        
        if($medvar->save()){
            return Redirect::route('medvars.index')->withSuccess('Great! New Medicine Variant updated successfully.');
        }
        
        return Redirect::route('medvars.index')->withError('Sorry! New Medicine Variant updated Failed.');
        
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function delete($id)
    {
        Medvariant::destroy($id);
        return Redirect::route('medvars.index')->withSuccess('Great! Medicine Variant deleted successfully.');
    }
    

}

Ehas/resources/views/admins/meds/medvars/create.blade.php
@extends('layouts.back-app')

@section('content')

    <div class="page-header">
        <div class="page-block">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <div class="page-header-title">
                        <h5 class="m-b-10">{{ $module }}</h5>
                    </div>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}"><i class="feather icon-home"></i></a></li>
                        <li class="breadcrumb-item"><a href="#!">{{ $module }}</a></li>
                            <li class="breadcrumb-item"><a href="#!">Create</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


	<div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                   <div class="d-flex">
                		<div class="col">
                			 <h5>Create a {{$module}} </h5>
                		</div>
                		<div class="col text-right">
                			<a class="btn btn-sm btn-primary" href="{{ route('medvars.index') }}"> <i class="feather icon-list"></i>{{$module}} List</a>
                		</div>
                	</div>
                </div>
                <div class="card-body">
                
                <div class="row">
                    <div class="col-12">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif
                        
                        {{-- <li class="breadcrumb-item active">Dashboard</li> --}}
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success alert-block">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                        <br>
                        @endif
                    </div>
                </div>
                
                    <form action="{{ route('medvars.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label class="floating-label" for="title">Title</label>
                                    <input type="text" name="title" class="form-control" id="title" aria-describedby="nameHelp" value="{{ old('title') }}">
                                </div>
                                
                              	<div class="form-group">
                                   <label for="short_desc">Details</label>
                                   <textarea class="form-control" name="details" id="details"  rows="3">{{ old('details') }}</textarea>
                               	</div>
                               
                                <div class="form-group">
                                    <label for="status">Status</label>
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" class="custom-control-input"  name="status" id="status">
                                        <label class="custom-control-label" for="status">Status</label>
                                    </div>        
                                </div>
                            </div>
                        </div>
                        <div class="row">
                        	<div class="col-sm-12">
                        		<button class="btn  btn-primary w-100" type="submit">Add {{$module}}</button>
                        	</div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

Ehas/resources/views/admins/meds/medvars/edit.blade.php
@extends('layouts.back-app')

@section('content')

    <div class="page-header">
        <div class="page-block">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <div class="page-header-title">
                        <h5 class="m-b-10">{{ $module }}</h5>
                    </div>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}"><i class="feather icon-home"></i></a></li>
                        <li class="breadcrumb-item"><a href="#!">{{ $module }}</a></li>
                            <li class="breadcrumb-item"><a href="#!">Update  {{ $module }}</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


	<div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                   <div class="d-flex">
                		<div class="col">
                			 <h5>Update {{$module}}</h5>
                		</div>
                		<div class="col text-right">
                			<a class="btn btn-sm btn-primary" href="{{ route('medvars.index') }}"> <i class="feather icon-list"></i> {{$module}} List</a>
                		</div>
                	</div>
                </div>
                <div class="card-body">
                
                <div class="row">
                    <div class="col-12">
                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif
                        
                        {{-- <li class="breadcrumb-item active">Dashboard</li> --}}
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success alert-block">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            <strong>{{ $message }}</strong>
                        </div>
                        <br>
                        @endif
                    </div>
                </div>
                
                    <form action="{{ route('medvars.update', $data->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
					@method('Patch')
                        <div class="row">
                            <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="floating-label" for="title">Title</label>
                                        <input type="text" name="title" class="form-control" id="title" aria-describedby="nameHelp" value="{{ $data->title }}">
                                    </div>
                                    
                              	<div class="form-group">
                                   <label for="short_desc">Details</label>
                                   <textarea class="form-control" name="details" id="details"  rows="3">{!! $data->details !!}</textarea>
                               	</div>
                                    
                                    <div class="form-group">
                                        <label for="status">Status</label>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input"  name="status" id="status" {{ $data->status == 1 ? 'checked' : '' }}>
                                            <label class="custom-control-label" for="status">Status</label>
                                        </div>        
                                    </div>
                            </div>
                        </div>
                        <div class="row">
                        	<div class="col-sm-12">
                        		<button class="btn  btn-primary w-100" type="submit">Update {{$module}}</button>
                        	</div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

Ehas/resources/views/admins/meds/medvars/index.blade.php
@extends('layouts.back-app')

@section('content')

	<style>
        .pagination {
            justify-content: center !important;
        }    
    </style>
    
    <div class="page-header">
        <div class="page-block">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <div class="page-header-title">
                        <h5 class="m-b-10">{{ $module }}</h5>
                    </div>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{route('admin.dashboard')}}"><i class="feather icon-home"></i></a></li>
                        <li class="breadcrumb-item"><a href="#!">{{ $module }}</a></li>
                            <li class="breadcrumb-item"><a href="#!">List</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


	<div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                   <div class="d-flex">
                		<div class="col">
                			 <h5>{{$module}} List</h5> 
                		</div>
                		<div class="col text-right">
                			<a class="btn btn-sm btn-primary" href="{{ route('medvars.create') }}"> <i class="feather icon-plus-square"></i> Add New</a>
                		</div>
                	</div>

                </div>
                <div class="card-body">
                
           			<div class="row">
                        <div class="col-12">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                        
                            {{-- <li class="breadcrumb-item active">Dashboard</li> --}}
                            @if ($message = Session::get('success'))
                               <div class="alert alert-success alert-block">
                                  <button type="button" class="close" data-dismiss="alert">×</button>
                                  <strong>{{ $message }}</strong>
                               </div>
                               <br>
                            @endif
                        </div>
                    </div>   
                                 
                	<table id="medvars-table" class="table table-condensed">
                    <thead>
                        <tr>
                            <th>SL.</th>
                            <th>Created At</th>
                            <th>Title</th>
                            <th>Details</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    	@if(isset($data) && count($data))
                   	 	@foreach($data as $item)
                    	<tr>
                    		<td>{{ $loop->iteration }}</td>
                    		<td>
                    			{{ $item->created_at->diffForHumans() }}
                    		</td>
                    		<td>
                    			<p> {{ $item->title }} </p>
                    		</td>
                    		<td>
                    			<p> {!! $item->details !!} </p>
                    		</td>
                    		<td>
                    			<div class="form-group">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" class="custom-control-input" {{ $item->status == 1 ? 'checked' : '' }} data-table="medvariants" data-id="{{$item->id}}" name="status" id="status-{{$item->id}}">
                                        <label class="custom-control-label" for="status-{{$item->id}}"></label>
                                    </div>        
                                </div>
                    		</td>
                    		<td>
                    			<p>
                        			<a class="btn btn-sm btn-primary" href="{{ route('medvars.edit', $item->id) }}">Edit</a>
                        			<button type="button" class="btn btn-sm btn-danger" data-toggle="popover" data-html="true" data-placement="top" title="<b>Are You Sure?</b>" data-content="<a class='btn btn-sm btn-info cancel-pop mx-2' href='#'>No</a><a class='btn btn-sm btn-danger mx-2' href='{{ route('medvars.delete', $item->id) }}'>Yes</a>">Delete</button>
                    			</p>
                    		</td>
                    	</tr>
                    	@endforeach
                    	@endif	
                    </tbody>
                	</table>
                    <div class="row justify-content-md-center">
                        <div class="col-6 col-sm-6">
        					{{ $data->appends(request()->query())->links() }}
                        </div>
                    </div>            
                
                </div>
            </div>
        </div>
    </div>
@endsection

@section('java_script')
	<script>
		$(function(){
			$(document).on('click', '.cancel-pop', function(e){
				e.preventDefault();
				$("[data-toggle='popover']").popover('hide');
			});
		});
	</script>
@endsection